const products = [
  {
    id: 1,
    name: "Modern Armchair",
    category: "armchair",
    price: 599.99,
    image: "Furniture images/armchair-1.jpg",
  },
  {
    id: 2,
    name: "Luxury King Bed",
    category: "bed",
    price: 1299.99,
    image: "Furniture images/bed-1.jpg",
  },
  {
    id: 3,
    name: "Open Wardrobe",
    category: "closet",
    price: 899.99,
    image: "Furniture images/closet-1.jpg",
  },
  {
    id: 4,
    name: "Oak Closet",
    category: "closet",
    price: 1099.99,
    image: "Furniture images/closet-2.jpg",
  },
  {
    id: 5,
    name: "Fancy Closet",
    category: "closet",
    price: 1499.99,
    image: "Furniture images/closet-3.jpg",
  },
  {
    id: 6,
    name: "Classic Dresser",
    category: "dresser",
    price: 749.99,
    image: "Furniture images/dresser-1.jpg",
  },
  {
    id: 7,
    name: "Black Dresser",
    category: "dresser",
    price: 799.99,
    image: "Furniture images/dresser-2.jpg",
  },
  {
    id: 8,
    name: "Velvet Sofa",
    category: "sofa",
    price: 1599.99,
    image: "Furniture images/sofa-1.jpg",
  },
  {
    id: 9,
    name: "Fancy Sectional",
    category: "sofa",
    price: 1899.99,
    image: "Furniture images/sofa-2.jpg",
  },
  {
    id: 10,
    name: "Contemporary Sofa",
    category: "sofa",
    price: 1399.99,
    image: "Furniture images/sofa-3.jpg",
  },
  {
    id: 11,
    name: "Living Room Table",
    category: "table",
    price: 399.99,
    image: "Furniture images/table-1.jpg",
  },
  {
    id: 12,
    name: "Dining Table",
    category: "table",
    price: 899.99,
    image: "Furniture images/table-2.jpg",
  },
];
